### ISSUE TITLE
"Entity could not be retrieved: HTTP status code: 401" from local-installed Node-Red

### ISSUE THREAD

**Issue by kikuzo** [lets-fiware/FIWARE-Big-Bang#149]
I want to access to orion context broker (installed by FIWARE B.B.) from locally installed Node-Red.

I could access to orion from Node-Red which was installed by FIWARE B.B.

![スクリーンショット 2022-02-08 1 18 10](https://user-images.githubusercontent.com/11046816/152827905-06248651-d5f9-49f7-b7e4-d52d078619e4.png)

I installed Node-Red to my local-PC and configured as same, but could not access.

![スクリーンショット 2022-02-08 1 20 11](https://user-images.githubusercontent.com/11046816/152828258-a3326a0b-d435-44af-9c85-17f2d64c614b.png)

I could not find what's wrong. I suppose something bad when passing through the authentication.
Do you have any ideas ?

**Comment by fisuda** [comment]
The HTTP status code 401 is  `Unauthorized`. There is something wrong with your credentials settings.
Please set your keyrock host, client id and client secret.

Thd IdM Endpoint is `https://keyrock.exmaple.com` or `https://keyrock.exmaple.com/oauth2/token`

```
$ cat .env | grep IDM_HOST
IDM_HOST=https://keyrock.exmaple.com
PEP_PROXY_IDM_HOST=keyrock
```

```
$ cat .env | grep TOKENPROXY_CLIENT
TOKENPROXY_CLIENT_ID=38684eeb-d58d-468b-b3be-7de420ed776f
TOKENPROXY_CLIENT_SECRET=37376a1f-b3e7-4815-9e23-44711dfc5703
```

**Comment by kikuzo** [comment]
Thank you for your quick reply.

I succeeded by setting PEP Proxy config (Client ID and Client Secret).
![スクリーンショット 2022-02-08 9 17 23](https://user-images.githubusercontent.com/11046816/152894185-6855632f-7bac-45ae-8c0a-10de858424db.png)

Thanks.

**Comment by fisuda** [comment]
Thank you for the feedback.

The Context-Broker node is modified to support the Tokenproxy feature in FI-BB. The source code is [here](https://github.com/lets-fiware/FIWARE-Big-Bang/blob/v0.10.0/CONTRIB/node-red-contrib-FIWARE_official/contextbroker.js). You should set your Keyrock host, username, password, client id and client secret when using the original Context-Broker node. So, I added an example to run Node-RED with the modified Context-Broker node locally by PR #150.

You can use the modified Context-Broker node in a Node-RED instance installed on your local PC when you start up a Node-red instance as shown: 

```
git clone https://github.com/lets-fiware/FIWARE-Big-Bang.git
cd FIWARE-Big-Bang/extras/node-red/
docker-compose build
docker-compose up -d
```

Then you set your Orion host, username, password to the Context-Broker node.

I ask you to review it. Please close this issue if it is ok.

p.s. If you think FIWARE Big Bang is the recommended tool for engineers, I would appreciate it if you could provide a Github Star to this repository. 😃 

Thanks!

**Comment by kikuzo** [comment]
Thank you for your kindly support.
I tried and success.

I set orion host(in IdM Endpoint field), Username and Password. not fill in PEP Proxy Client ID and Client Secret.

Thanks.
