### ISSUE TITLE
PostgreSQL version update

### ISSUE THREAD

**Issue by dkastl** [lets-fiware/FIWARE-Big-Bang#230]
In `config.sh` the PostgreSQL Docker container specifies version 11: https://github.com/lets-fiware/FIWARE-Big-Bang/blob/main/config.sh#L443-L444

This is a rather old version of PostgreSQL and it will reach "end-of-life" in November 2023: https://www.postgresql.org/support/versioning/

What would be the highest possible PostgreSQL version considering all the projects that make use of it?

**Comment by fisuda** [comment]
Thank you for the feedback.
Merged PR #241. PostgreSQL was updated to version 15.
