### ISSUE TITLE
lets-fiware.sh script deletes data directory

### ISSUE THREAD

**Issue by dkastl** [lets-fiware/FIWARE-Big-Bang#234]
Running the `lets-fiware.sh` command again on an existing installation deletes the `/data` directory, which (in my understanding) is supposed to store persistent data:
https://github.com/lets-fiware/FIWARE-Big-Bang/blob/main/lets-fiware.sh#L3511-L3513

From a user perspective it's slightly unexpected that running `lets-fiware.sh` creates a fresh installation and also removes the data directory. I'm not sure it's necessary to delete all the data, but here are a few suggestions how to improve this:

1. Add some context to the documentation that all data will be deleted and that `lets-fiware.sh` should only be used for the initial setup
2. Add an optional command line parameter that needs to be set in order to delete the data
3. Ask/confirm to delete the data when running the script 

I thought it would be nice if `lets-fiware.sh` could be also run to update an existing setup.

**Comment by fisuda** [comment]
Thank you for the feed back. Merged PR #239
The `letsfiware.sh` script execution aborts if there is a data directory.
