### ISSUE TITLE
NODE_RED_INSTANCE_NUMBER out of range with `1`

### ISSUE THREAD

**Issue by dkastl** [lets-fiware/FIWARE-Big-Bang#373]
**Checklist**
_Put an `x` in the boxes that apply_

-   \[x\] I have run the latest release.
-   \[ \] I have inspeced the status of docker containers.
-   \[ \] I have run the sanity check described in after-installation.md.
-   \[ \] I have inspected all error messages.
-   \[ \] I have inspected the log files in the /var/log/fiware directory.
-   \[ \] I have run the `make collect` command.
-   \[ \] I have provided a Github Star to this repository.

**Describe the bug**

When I specify

```sh
NODE_RED_INSTANCE_NUMBER=1
```

an error is thrown like

```
error: NODE_RED_INSTANCE_NUMBER out of range (2-20)
```

However, if the setting is without explicit value

```sh
NODE_RED_INSTANCE_NUMBER=
```

Then 1 instance is created as the default value claims: https://github.com/lets-fiware/FIWARE-Big-Bang/blob/main/config.sh#L314

**Your system environment**

This is independent from the system environment.

**To Reproduce**

See above.

**Expected behavior**

Probably specifying `1` for `NODE_RED_INSTANCE_NUMBER` should not produce an error and create a single Nodered instance as the default does.

**Screenshots**

**Server (please complete the following information):**
-   OS and OS version:
-   Docker version:
-   Docker Compose version:

**Additional context**
To resolve this issue, you need to provide complete information about your scenario.

**Comment by fisuda** [comment]
Fixed by the PR #375.
