### ISSUE TITLE
pwgen command not found

### ISSUE THREAD

**Issue by dogfoodlab** [lets-fiware/FIWARE-Big-Bang#5]
Hello,
Error occurs because pwgen is run before installing yum package.

- OS: CentOS7

```
$ ./lets-fiware.sh example.com xx.xx.xx.xx
./lets-fiware.sh: line 54: pwgen: command not found
```

I wrote the following and it worked.

lets-fiware.sh
```sh
SETUP_DIR=./setup
${SETUP_DIR}/prepare.sh

IDM_ADMIN_EMAIL_NAME=admin
IDM_ADMIN_PASS=$(pwgen -s 16 1)

DATA_DIR=./data
CERT_DIR=$(pwd)/data/cert
CONFIG_DIR=./config
```

Also, pwgen and jq are dependent on epel.
I rewrote prepare.sh as follows.

```sh
install_commands_centos() {
  sudo yum install -y epel-release
  sudo yum install -y curl pwgen jq
}
```

**Comment by fisuda** [comment]
Thank you very much for interesting in FIWARE Big Bang and your feedback!

I fixed it. Please test it and close this issue if all works as expected.

**Comment by dogfoodlab** [comment]
Thanks, It work fine.
